spring:
  application:
    name: eureka-gateway

  config:
    import: "optional:configserver:http://3.37.74.44:8888"
  cloud:
    config:
      fail-fast: true #Config 서버 연결 실패 시 어플리케이션 시작 실패

# Actuator 설정 (설정 갱신을 위해 필요한 경우)
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info